package bokuweb:image-diff;

interface types {
  record output {
    // The number of pixels that differ between the two images.
    diff-count: u32,
    // The buffer of the difference image in `WebP` format.
    diff-image: list<u8>,
    // The width of the difference image.
    width: u32,
    // The height of the difference image.
    height: u32,
  }

  record opts {
    // Matching threshold, ranges from 0 to 1. Smaller values make the comparison more sensitive. 0.1 by default.
    threshold: option<float32>,
    // The flag of antialias. If omitted false.
    include-anti-alias: option<bool>,
  }

  variant error {
    decode(string),
    encode(string),
  }
}

world image-diff {

  use types.{opts, output, error};

  // The diff function is designed to compare two images and identify their differences.
  export diff: func(imga: list<u8>, imgb: list<u8>, opts: opts) -> result<output, error>;
}