[package]
name = "image-diff-wasm"
version = "0.1.0"
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
image-diff-rs= { path = "../core" }
wit-bindgen = "0.14.0"

[lib]
crate-type = ["cdylib"]
